### ISSUE TITLE
Add typescript definition file

### ISSUE THREAD

**Issue by danimbrogno** [DeadAlready/easy-rbac#2]
Using this module with typescript, wrote this ts.d file, but I'm not confident enough to submit to the @types repository. Thought I'd put it up here to get feedback before submitting.

```

declare module "easy-rbac" {

    interface when {  
        (theNumber: number) : number;
    }

    interface canObj {
        name: string;
        when: (params:any, callback:() => void) => void;
    }

    interface opts {
        [propName: string]: {
            can: (string | canObj)[],
            inherits?: string[]
        }
    }

    class RBAC {

        constructor(opts:opts);

        can(role: string, operation: string, cb?: (err: any, can: boolean) => void): void;
        can(role: string, operation: string, params?:any): Promise<void>;

        static create(opts: opts): RBAC

    }

    export = RBAC;

}
```

**Comment by danimbrogno** [comment]
Previous version wouldn't allow you to instantiate easy rbac with `new RBAC()` when using es6 style imports, i.e. `import * as RBAC from 'easy-rbac'`.

New version:

```
declare module "easy-rbac" {

    interface when {  
        (theNumber: number) : number;
    }

    interface canObj {
        name: string;
        when: (params:any, callback:() => void) => void;
    }

    interface opts {
        [propName: string]: {
            can: (string | canObj)[],
            inherits?: string[]
        }
    }

    export = class {

        constructor(opts: opts);

        can(role: string, operation: string, cb?: (err: any, can: boolean) => void): void;
        can(role: string, operation: string, params?:any): Promise<void>;

        static create(opts: opts): any;

    }

}
```

however you must use require style import:

`import RBAC = require('easy-rbac');`

**Comment by DeadAlready** [comment]
I don't have a convenient typescript setup to validate - so until I do the setup my first observations:
1. when interface ? - I don't understand the point of this
2. The can function is missing a possible invocation of having both cb and params

**Comment by danimbrogno** [comment]
1. Right on, that interface isn't used at all.
2. Good catch. I'll add that.

One other question, in the docs it says "Each role must have a can property, which is an array". Is this strictly true? What if you had a role that simply inherits another role (I guess this would be like a role alias). Is that an unsupported configuration?

Would you accept a PR that adds this typing into the library, or would you prefer to go the route of adding the typings to the @types project?

**Comment by DeadAlready** [comment]
Each role must have an array - otherwise an error will be thrown. However it can be an empty array if you want it to be an alias of another role.

One more thing I noticed in the .d.ts - shouldn't the static create method return a reference to the class ? It will work if it is any, but the autocomplete will be a bit broken.

If you do a pull request I'll accept it..
