### ISSUE TITLE
rbac.can should be able to accept array of operations as input 

### ISSUE THREAD

**Issue by chromonav** [DeadAlready/easy-rbac#3]
I have multiple operations that need checked before giving the access. 
If all the operations are valid then rbac should return true else err
Looping through promises and waiting for them seems ugly.

**Comment by DeadAlready** [comment]
I don't see that this should be supported by the library.

In general operations are supposed to be granular permissions and you should be checking for the corresponding operation permission at the operation time. 
(Refer to https://www.owasp.org/index.php/Top_10_2013-A7-Missing_Function_Level_Access_Control)

And leaving that aside if you still need multiple checks I would just do:

```
Promise.all([
    rbac.can('user', 'first operation'),
    rbac.can('user', 'second operation'),
    rbac.can('user', 'third operation')
])
.then(() => {
    console.log('user is qualified for all');
}).catch(err => {
    console.log('at least one fails');
});
```
