### ISSUE TITLE
Not responding when checking with inherited conditional operation resulting unauthorized

### ISSUE THREAD

**Issue by bhargav-sae** [DeadAlready/easy-rbac#4]
It is not responding when I am checking an inherited conditional operation resulting unauthorized.
```
let roles = {
  user: {
    can: [{
      name: "account:view", // can view own account
      when: function(param, callback) {
         setImmediate(callback, null, false); // always false, just for test.
      }
    }]
  },
  writer: {
    can: ["post:create", {
      name: "post:update",
      when: function(param, callback) {
         setImmediate(callback, null, if(own by writer));
      }
    }],
    inherits: ["user"]
  },
  admin: {
    can: ["anything"],
    inherits: ["writer"]
  }
}
```

when I try to check if `writer` is allowed to `account:view` or not, it never responds when its `false`.
But for conditional operation resulting `true` it works perfect.

**When I say `responds`, meaning Callback execution**

**Comment by DeadAlready** [comment]
The underlying Q library has changed the way it operates. It no longer accepts 'false' as the reject value - and since easy-rbac sent false to the reject it just ignored it and nothing happened.

I have changed it now to reject with Error('unauthorized')

**Comment by bhargav-sae** [comment]
Thanks for quick reply and solution.

**Comment by MarkHerhold** [comment]
@DeadAlready Would you be open to a PR removing `Q` altogether? All stable/LTS Node.js versions now have native promise support.

**Comment by DeadAlready** [comment]
Sure.
The only reason I had Q in the first place was for legacy support and because it has the .any function which has no equivalent in the native implementation. But that was years ago, so I think it's fine to move on from Q.
