### ISSUE TITLE
Some tests fail since Q.any throws different messages

### ISSUE THREAD

**Issue by fthuin** [DeadAlready/easy-rbac#6]
Hello,

Q changed the way it handles the error message when a Q.any does not return fulfillment value.

```javascript
err.message = ("Q can't get fulfillment value from any promise, all " +
                      "promises were rejected. Last error message: " + err.message);
```

see commit https://github.com/kriskowal/q/pull/740/files#diff-a148bc52a39c990d02038097d8177455R1628

So the tests are not valid anymore, because err.message is not anymore equals to `'unauthorized'` but instead it is `'Q can't get fulfillment value from any promise, all promises were rejected. Last error message: unauthorized'`

**Comment by DeadAlready** [comment]
Sry for the delay in fixing. I was on a long vacation without my computer.

I have released v2.1.3 which includes a handling of the error fitting both the old and new versions.
